# Generated by Django 4.2.2 on 2023-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='Nil', max_length=255)),
                ('location_job', models.CharField(default='Nil', max_length=300)),
                ('department', models.CharField(default='Nil', max_length=255)),
                ('company_profile', models.TextField(default='Nil', max_length=1000)),
                ('job_description', models.TextField(default='Nil', max_length=1000)),
                ('job_requirements', models.TextField(default='Nil', max_length=1000)),
                ('job_benefits', models.TextField(default='Nil', max_length=1000)),
                ('employment_type', models.CharField(default='Nil', max_length=255)),
                ('required_experience', models.CharField(default='Nil', max_length=255)),
                ('required_education', models.CharField(default='Nil', max_length=255)),
                ('industry', models.CharField(default='Nil', max_length=255)),
                ('job_function', models.CharField(default='Nil', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_benefits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_function',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_requirements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location_job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='required_education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='required_experience',
        ),
    ]
