# Generated by Django 4.2.2 on 2023-11-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companionapp', '0002_job_posting_remove_user_company_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_posting',
            name='companyid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
