# Generated by Django 4.2.2 on 2023-12-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companionapp', '0004_job_posting_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
    ]
