# Generated by Django 4.2.7 on 2023-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companionapp', '0005_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingid', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('companyid', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('location_job', models.CharField(blank=True, default='Nil', max_length=300, null=True)),
                ('department', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('company_profile', models.TextField(blank=True, default='Nil', max_length=1000, null=True)),
                ('job_description', models.TextField(blank=True, default='Nil', max_length=1000, null=True)),
                ('job_requirements', models.TextField(blank=True, default='Nil', max_length=1000, null=True)),
                ('job_benefits', models.TextField(blank=True, default='Nil', max_length=1000, null=True)),
                ('employment_type', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('required_experience', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('required_education', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('industry', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
                ('job_function', models.CharField(blank=True, default='Nil', max_length=255, null=True)),
            ],
        ),
    ]
