# Generated by Django 4.2.7 on 2023-12-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companionapp', '0006_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_messsage',
            field=models.TextField(blank=True, default='Nil', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='application_status',
            field=models.BooleanField(default=False, verbose_name='Application Status'),
        ),
    ]
